name: spotify-ai-playlists
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - langchain
    - langchain-community
    - openai
    - spotipy
    - python-dotenv
